FIX compatibility with symbolic link
altairisfr/DoliSIRH pull request #1
Opened 2023-05-10 07:34 UTC by hregis

2023-05-10 08:40 UTC, altairis-noe requested changes
À part la suppression du changelog, ça ma paraît bien

2023-05-10 08:40 UTC, altairis-noe commented on ChangeLog.md
> -Initial version
Pourquoi supprimer le ChangeLog ?

2023-05-10 08:41 UTC, hregis commented on ChangeLog.md
> -Initial version
@altairis-noe aucune idée, il n'était pas présent dans la branche develop !!

2023-05-10 08:43 UTC, altairis-noe commented on ChangeLog.md
> -Initial version
Apparemment si, puisque la PR le supprime ! 🤔

2023-05-10 08:59 UTC, hregis commented on ChangeLog.md
> -Initial version
@altairis-noe il m'a demandé de le supprimer... va comprendre

2023-07-03 08:04 UTC, altairis-noe commented on ChangeLog.md
> -Initial version
J’ai compris @hregis : MacOS est insensible à la casse, et le projet d’origine comporte un changelog.md et un ChangeLog.md 🤪

2023-07-03 09:10 UTC, altairis-tof commented on class/actions_dolisirh.class.php
> +			if (GETPOST('action') == 'presend_addmessage' || GETPOST('action') == 'add_message') {
@hregis @altairis-noe je débarque peut-être mais que fout dolisirh ici ??? c'est inclus dans le core ???

2023-08-11 17:42 UTC, merged